CREATE TABLE T_Province(
  ProID INT PRIMARY KEY AUTO_INCREMENT,
  ProName NVARCHAR(50) NOT NULL,
  ProSort INT,
  ProRemark NVARCHAR(50)
);

CREATE TABLE T_City
(
	CityID INT Primary KEY AUTO_INCREMENT,
	CityName NVARCHAR(50)  NOT NULL,
	ProID INT,
	CitySort INT
);

CREATE TABLE  T_District
(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	DisName NVARCHAR(30) NOT NULL,
	CityID INT NOT NULL,
	DisSort INT
);